# Generated by Django 6.0.3 on 2026-08-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_shopitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='category',
            field=models.CharField(choices=[('general', '一般'), ('avatar', '角色'), ('pet', '寵物'), ('emoji', '表情'), ('background', '背景'), ('badge', '徽章'), ('powerup', '道具')], default='general', max_length=30),
        ),
    ]
