# Generated by Django 6.0.3 on 2026-09-15 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_post_emoji_reply_emoji_and_blank_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='selected_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.shopitem'),
        ),
    ]
