# Generated by Django 4.2 on 2026-09-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_alter_shopitem_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_choice",
            field=models.CharField(
                choices=[
                    ("default1", "預設頭像 1"),
                    ("default2", "預設頭像 2"),
                    ("default3", "預設頭像 3"),
                    ("default4", "預設頭像 4"),
                    ("custom", "自訂頭像"),
                ],
                default="default1",
                max_length=20,
            ),
        ),
    ]
