# Generated by Django 4.2 on 2026-09-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_post_emoji_reply_emoji_and_blank_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopitem",
            name="image",
        ),
        migrations.AddField(
            model_name="shopitem",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
