# Generated by Django 4.2 on 2026-09-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_remove_shopitem_image_shopitem_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="avatar",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
