# Generated by Codex on 2026-08-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_levelunlock"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "一般"),
                    ("avatar", "角色"),
                    ("background", "背景"),
                    ("badge", "徽章"),
                    ("powerup", "道具"),
                ],
                default="general",
                max_length=30,
            ),
        ),
    ]
